### ISSUE TITLE
Nefunguje - narozeniny, nejsou videt v náhledu pro zaměstnace.

### ISSUE THREAD

**Issue by novakhonza1** [MichalBryxi/kasa#179]
a nefunguje ukazatel blížících se narozenin
![pasted_image_23_01_17_20_24](https://cloud.githubusercontent.com/assets/25285324/22219203/2f1f1d3e-e1aa-11e6-8b82-31871039112b.png)

**Comment by MichalBryxi** [comment]
Fixed.
