### ISSUE TITLE
tisk účtenek

### ISSUE THREAD

**Issue by novakhonza1** [MichalBryxi/kasa#191]
- připravit stránku s údaji pro tisk účtenky
- dostat to do fáze kdy se po kliknutí na nové tlačítko "uzavřít a tisknout" otevže dialog "CTR+P"

![uctenka](https://cloud.githubusercontent.com/assets/847473/22628785/b3f841ae-ebda-11e6-962e-1dd130183de3.jpg)

**Comment by MichalBryxi** [comment]
This is done.
